### ISSUE TITLE
Possibility to support 64-bit some day?

### ISSUE THREAD

**Issue by stefanos82** [pacman128/pcasm#1]
@pacman128 First of all, thank you very much for the book, it looks amazing.

As the title says, are there any plans to support 64-bit in the near future? I'm currently teaching myself assembly using my Linux system and I'm facing some issues with some material I have found online.

Some websites teach assembly while using Intel's syntax and some AT&T's, which is confusing me a lot.

By the way, would it be a problem if the book's style change a bit? I'm quite comfortable using LaTeX and one of my eccentricities is producing good-looking ebooks.

Right now I'm trying to mimic the look of [this book](http://jeffe.cs.illinois.edu/teaching/algorithms/all-algorithms.pdf) which has one of the most appealing styles I have ever seen.

Are you open for such change or should I use it for my own version?

Cheers.

**Comment by pacman128** [comment]
There's not much chance I'm going to do this. I looked into this, but it would take an immense amount of time to do this well. I taught myself 32-bit assembly when I was teaching (and before kids) when I had lots of time to pursue projects like this. I'm a full time developer now and don't have the time now.

However, one of the reasons I've started to put this up on github is to allow others to adapt my text for projects just like this. In next few weeks, I should be putting up the different language translations and formalizing a license.

**Comment by stefanos82** [comment]
No worries. I'm looking forward to see how this project is going to evolve.

**Comment by lighterowl** [comment]
I've been going through the book and listing things that would need changing if 64-bit support was introduced. However, the more I read, the more I'm convinced that the only way to do this that makes sense is to effectively create a branch of the book. This way, all the information already available in the 32-bit version of the book remains accurate and available, while at the same time not being clobbered with a lot of "32 does it this way, 64 does it differently" phrases.
Choice of the processor's bitness affects pretty much everything :
 * supported development environments (compiling and running 64-bit code with DJGPP and running it under DOS would be... interesting),
 * object file formats (OMF doesn't support 64-bit code, for example),
 * stack addressing and alignment (32-bit mode supported dword-sized push/pop instructions, 64-bit mode requires qwords),
 * practically all the author-provided routines and examples,
 * calling conventions,
 * a lot of other stuff.
