### ISSUE TITLE
about the +56(00111000) one's complement

### ISSUE THREAD

**Issue by sherwinl1u** [pacman128/pcasm#6]
why the book says the +56(00111000) one's complement is 11000111 on the page 28 (Chapter2)

I think the one's complement and two's complement is the equal to 00111000, because it's a Positive integer

am i right?

**Comment by pacman128** [comment]
One's component is an _operation_ that reverses the bits of a _value_. So the one's component of 00111000 is 11000111 by definition, just as the one's complement of 11000111 is 00111000. The operation is its own inverse (just like negation -(-10) = 10).

It has nothing to do with whether the bits represent a positive or negative value. At the assembly level, what the bits represent depend on how the bits are used. For example, 11111111 can represent the signed 8-bit value -1 or the unsigned 8-bit value 255. The CPU has no idea which is correct, it all depends on what instructions are used on the bits. In high level languages like C, you tell the compiler which representation to use by the variable type and the compiler generates the corresponding CPU instructions based on the variable type.
